refactor: error as any switched to error as unknown
error: any becomes error:unknown without affecting code function and
addresses new linting rule no-explicit-any